(define (first-denomination coin-values) (car coin-values))

(define (except-first-denomination coin-values) (cdr coin-values))

(define (no-more? coin-values) (null? coin-values))


The answer does not depend on the order of the list because cc exhaustively traverses the list when calculating the answer.
Recall that the process generated by cc takes the shape of a tree. It terminates the evaluation of a branch only when the list is empty or when the amount of change remaining is less than or equal to zero. 
